name: 'Run Nomad Job'
description: 'Handles running of a given nomad job'
inputs:
  auth:
    description: 'Base64 encoded version of username:password to access the nomad server'
    required: true
  address:
    description: 'Address of the nomad server'
    required: true
  job:
    description: 'Path to the nomad job file'
    required: true
  datacenters:
    description: 'Alternative list of datacenters for deployment if default in job-file are not used'
    required: false
    default: ''
  node_pool:
    description: 'Overwrite node_pool in job file'
    required: false
    default: ''
  tag:
    description: 'Use GITHUB_NAME_REF as dosker tag'
    required: false
    default: ''
  count:
    description: 'Overwrite number of deployments in job file'
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.auth }}
    - ${{ inputs.address }}
    - ${{ inputs.job }}
    - ${{ inputs.datacenters }}
    - ${{ inputs.node_pool }}
    - ${{ inputs.tag }}
    - ${{ inputs.count }}
branding:
  icon: 'upload-cloud'
  color: 'gray-dark'